services:
  demo-app:
    build: ./demo-app
    container_name: demo-app
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 2s
      retries: 10

  e2e-demoapp:
    build: ./e2e-framework
    container_name: e2e-tests-demoapp
    depends_on:
      demo-app:
        condition: service_healthy
    entrypoint: ["bash", "entrypoint.sh"]
    environment:
      CONFIG_FILE: demoapp.docker.yaml
      PYTEST_MARK: app_demoapp
    volumes:
      - ./e2e-framework/reports:/app/reports
      - ./e2e-framework/logs:/app/logs

  e2e-demoqa:
    build: ./e2e-framework
    container_name: e2e-tests-demoqa
    environment:
      CONFIG_FILE: demoqa.local.yaml
      PYTEST_MARK: app_demoqa
      SKIP_WAIT: "1"               
    volumes:
      - ./e2e-framework/reports:/app/reports
      - ./e2e-framework/logs:/app/logs
