version: '3.9'

services:
  e2e-tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../reports:/app/reports
    command: bash docker/entrypoint.sh

  allure-report:
    image: frankescobar/allure-docker-service:latest
    ports:
      - "8090:8080"
    volumes:
      - ../reports:/app/allure-results
    command: ["allure", "serve", "--port", "8080", "/app/allure-results"]
