[pytest]
addopts = -v --alluredir=reports/allure-results 
testpaths = src/tests
pythonpath = .

markers =
    app_demoqa: tests for demoqa app
    app_demoapp: tests for demoapp

    smoke: smoke tests
    api: api tests
    ui: ui tests
    regression: regression tests

    priority_low: Low priority
    priority_medium: Medium priority
    priority_high: High priority
    priority_critical: Critical priority

    severity_trivial: Trivial severity
    severity_minor: Minor severity
    severity_normal: Normal severity
    severity_critical: Critical severity
    severity_blocker: Blocker severity

filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning

log_cli = true
log_cli_level = DEBUG
log_cli_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

log_file = logs/tests.log
log_level = DEBUG
log_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_date_format = %Y-%m-%d %H:%M:%S

[allure]
results_dir = reports/allure-results